name: Deploy to GitHub Pages
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - run: pip install -r requirements.txt
      - run: python app.py & sleep 10
        background: true
      - name: Archive Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: |
            static/
            templates/
            app.py
